"""'init'

Revision ID: a8a9870df26d
Revises: 
Create Date: 2018-11-26 21:11:17.080225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a9870df26d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    project_table = op.create_table('project',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('click_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        project_table,
        [
            {'name': 'acme'},
            {'name': 'brain'}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_event')
    op.drop_table('click_event')
    op.drop_table('event')
    op.drop_table('project')
    # ### end Alembic commands ###
